services:
  nginx:
    image: tugboat/ngnix
    default: true
    depends: node
    commands:
      init:
        - ln -snf "${TUGBOAT_ROOT}/build" "${DOCROOT}"
  node:
    image: tugboatqa/node:16
    expose: 3000
    commands:
      update:
        - npm install
      build:
        - npm run build
      online:
        - rm -rf node_modules
